version: "3"

services:
  api:
    build:
      context: .
      dockerfile: ./api.dockerfile
    ports:
      - 8080:8080

  ui:
    build:
      context: .
      dockerfile: ./ui.dockerfile

    depends_on:
      - api

    ports:
      - 80:80