version: "3"

services:
  api:
    env_file:
      - ./.env
    image: richardpickman/munchkin-level-counter-api:alpha
    entrypoint: ['node', 'index.js']
    build:
      context: .
      dockerfile: ./api.dockerfile
    ports:
      - 8080:8080

  ui:
    build:
      context: .
      dockerfile: ./ui.dockerfile
    image: richardpickman/munchkin-level-counter-ui:alpha
    depends_on:
      - api

    ports:
      - 80:80