version: "3"

services:
  api:
    env_file:
      - ./.env
    image: richardpickman/munchkin-level-counter-api:alpha
    entrypoint: ["node", "index.js"]
    build:
      context: .
      dockerfile: ./api.dockerfile
    ports:
      - 8080:8080

  ui:
    env_file:
      - ./.env
    image: richardpickman/munchkin-level-counter-ui:alpha
    entrypoint: ["yarn", "ui:run"]
    build:
      context: .
      dockerfile: ./ui.dockerfile
    depends_on:
      - api

    ports:
      - 3000:3000
